// <auto-generated />
namespace SolutionPrincipale.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class mig4LongLat : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig4LongLat));
        
        string IMigrationMetadata.Id
        {
            get { return "201805171300571_mig4-LongLat"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
