// <auto-generated />
namespace SolutionPrincipale.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class mig20805241029 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig20805241029));
        
        string IMigrationMetadata.Id
        {
            get { return "201805240830044_mig208-05-24-10-29"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
